### ISSUE TITLE
Enviar ordem de serviço via email

### ISSUE THREAD

**Issue by ricardobsilva** [ricardobsilva/msmanager#10]
Ao criar uma ordem de serviço, o cliente deve receber um email informando que uma ordem de serviço foi gerada. 

Esse email deverá conter todos os dados relacionados a ordem de serviço (placa do veículo, número da ordem, serviços realizados, valor total, etc...)

**Comment by wilmasilva-24** [comment]
https://github.com/ricardobsilva/msmanager/pull/11#issue-1222392382
