### ISSUE TITLE
Hospedar aplicação no Heroku

### ISSUE THREAD

**Issue by ricardobsilva** [ricardobsilva/msmanager#13]
Link sobre o Heroku

https://www.heroku.com/about

https://levelup.gitconnected.com/all-you-need-to-know-about-heroku-in-5-minutes-7d4ec8849114

Documentação:

https://devcenter.heroku.com/articles/getting-started-with-rails6

**Comment by wilmasilva-24** [comment]
https://github.com/ricardobsilva/msmanager/pull/14
