### ISSUE TITLE
Criar opção de cadastrar tipos serviços

### ISSUE THREAD

**Issue by wilmasilva-24** [ricardobsilva/msmanager#6]
**Comportamento atual:**
Não tem opção de cadastrar os tipos de serviços.

![image](https://user-images.githubusercontent.com/81061845/164836574-61bb8744-4551-4b9a-8ba0-d521db43f5b0.png)

**Comportamento esperando:**
Cadastrar itens de serviços a executar.

**Passos para reproduzir o problema:**
Ordens de serviços - Serviços a executar - Item.

**Comment by ricardobsilva** [comment]
https://github.com/ricardobsilva/msmanager/pull/9
